import {registerEnumType} from '@nestjs/graphql';

export enum SlotType {
  SPORT = 'SPORT',
  TM_WITH_CAMERAMAN = 'TM_WITH_CAMERAMAN',
  TM_WITHOUT_CAMERAMAN = 'TM_WITHOUT_CAMERAMAN',
  STATIC_LINE = 'STATIC_LINE',
  AFF_TWO_INSTRUCTORS = 'AFF_TWO_INSTRUCTORS',
  AFF_ONE_INSTRUCTOR = 'AFF_ONE_INSTRUCTOR',
  COACHED_JUMP = 'COACHED_JUMP',
  HOP_ON_HOP_OFF = 'HOP_ON_HOP_OFF',
  PASSENGER = 'PASSENGER'
}

registerEnumType(SlotType, {
  name: 'SlotType',
});
